Export api
HSLdevcom/jore4-hastus pull request #5
Opened 2023-02-23 15:47 UTC by culka

Export API implementation

2023-02-27 11:36 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5)* status: 0 of 45 files reviewed, 9 unresolved discussions (waiting on @culka)

___
*[`README.md` line 40 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHSt9I6FH3ZvzvMrF3:-NPHSt9I6FH3ZvzvMrF4:b2nhe52) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/README.md#L40)):*
> ```Markdown
> The returned CSV file follows the Hastus CSV specification.
> 
> ## Technical DocumentationEi
> ```

Ei?
___
*[`profiles/dev/config.properties` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHTAT99rfEQxeo6jV1:-NPHTAT99rfEQxeo6jV2:bhvshde) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/profiles/dev/config.properties#L2)):*
> ```INI
> hasura.url=http://localhost:3201/v1/graphql
> hasura.secret=placeholder
> ```

let's add a comment here that the hasura admin secret is only used for fetching the graphql schema but is not used for running queries against the hasura endpoint.
let's also set this explicitly to "hasura", we shouldn't expect the user to fill this value in using an environment variable
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHVu65EEzz43Vp-NnE:-NPHVu65EEzz43Vp-NnF:biryuar) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt#L43)):*
> ```Kotlin
>         @RequestBody request: Routes,
>         @RequestHeader(HttpHeaders.COOKIE, required = false) cookieHeader: String?,
>         @RequestHeader("x-hasura-role", required = false) hasuraRole: String?,
> ```

let's add a comment here that the cookie and the headers are passed on the the hasura api, not used by the service itself. Let's also not accept x-hasura-admin-secret here as it's too easy to get lazy and use the secret instead of the auth hook.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/config/WebSecurityConfig.kt` line 29 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPH_ZeA1kKIUl7fxHfN:-NPH_ZeB5h23o7l_If60:boaw2df) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/config/WebSecurityConfig.kt#L29)):*
> ```Kotlin
>                 HttpMethod.POST,
>                 "/export/routes",
>                 "/export/lines"
> ```

export/lines doesn't exist anymore
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/format/NumberWithAccuracy.kt` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHWjHzCckUXGUVG2ID:-NPHWjHzCckUXGUVG2IE:bo7rftu) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/data/format/NumberWithAccuracy.kt#L10)):*
> ```Kotlin
>  * @property digits number of digits
>  */
> data class NumberWithAccuracy(val value: Number, val leading: Int, val digits: Int)
> ```

isn't there some Decimal type that could handle this better? Do you need an own type for this?ro
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/jore/JoreLine.kt` line 3 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHa00n1XeDSe4Psdqw:-NPHa00n1XeDSe4Psdqx:bvie35u) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/data/jore/JoreLine.kt#L3)):*
> ```Kotlin
> package fi.hsl.jore4.hastus.data.jore
> 
> data class JoreLine(
> ```

if you have energy, it would be nice to stop using the Jore* transfer types but map directly from the graphql types to the final Hastus* types
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt` line 102 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHaldX39QYMfGRQODt:-NPHaJ88EtcxJ-oy8xsg:bjkf4xf) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt#L102)):*
> ```Kotlin
>                 if (cookieToken != null) header("Cookie", cookieToken)
>                 if (hasuraRole != null) header("x-hasura-role", hasuraRole)
>                 if (hasuraSecret != null) header("x-hasura-admin-secret", hasuraSecret)
> ```

let's not use the x-hasura-admin-secret for queries, it's a security risk
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt` line 135 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHbJPQ28QCUusqn2W1:-NPHbJPQ28QCUusqn2W2:bjkf4xf) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt#L135)):*
> ```Kotlin
>                 if (cookieToken != null) header("Cookie", cookieToken)
>                 if (hasuraRole != null) header("x-hasura-role", hasuraRole)
>                 if (hasuraSecret != null) header("x-hasura-admin-secret", hasuraSecret)
> ```

let's not use the x-hasura-admin-secret for queries, it's a security risk
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/util/CsvWriter.kt` line 40 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHdh07A5j0VRUDOCeq:-NPHdh07A5j0VRUDOCer:b-ge641t) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/util/CsvWriter.kt#L40)):*
> ```Kotlin
>     }
> 
>     private fun formattedNumberTransform(number: NumberWithAccuracy): String {
> ```

should rather move this to the class's toString() method


<!-- Sent from Reviewable.io -->

2023-03-02 12:08 UTC, culka reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5)* status: 0 of 45 files reviewed, 9 unresolved discussions (waiting on @pallost)

___
*[`README.md` line 40 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHSt9I6FH3ZvzvMrF3:-NPWW7wy3SVSqW_LH6mU:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/README.md#L40)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Ei?
</blockquote></details>

Done.
___
*[`profiles/dev/config.properties` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHTAT99rfEQxeo6jV1:-NPWWHG96_otdUVTLXxn:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/profiles/dev/config.properties#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's add a comment here that the hasura admin secret is only used for fetching the graphql schema but is not used for running queries against the hasura endpoint.
let's also set this explicitly to "hasura", we shouldn't expect the user to fill this value in using an environment variable
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHVu65EEzz43Vp-NnE:-NPWfhYkBftPw4htdlmP:b-blyh7p) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt#L43)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's add a comment here that the cookie and the headers are passed on the the hasura api, not used by the service itself. Let's also not accept x-hasura-admin-secret here as it's too easy to get lazy and use the secret instead of the auth hook.
</blockquote></details>

Removed the admin secret here
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/config/WebSecurityConfig.kt` line 29 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPH_ZeA1kKIUl7fxHfN:-NPWg5Fe9csBD68ZPcoP:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/config/WebSecurityConfig.kt#L29)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

export/lines doesn't exist anymore
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/format/NumberWithAccuracy.kt` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHWjHzCckUXGUVG2ID:-NPWgTtY4oj8aCKhFSSO:bc3evwh) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/data/format/NumberWithAccuracy.kt#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

isn't there some Decimal type that could handle this better? Do you need an own type for this?ro
</blockquote></details>

No, I don't think there is one that allows you to specify leading and trailing zeroes. Only when printing them.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt` line 102 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHaldX39QYMfGRQODt:-NPWg73GB87i6DRwz_VV:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt#L102)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's not use the x-hasura-admin-secret for queries, it's a security risk
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt` line 135 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHbJPQ28QCUusqn2W1:-NPWg7I-8QX6ujyKwj9I:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt#L135)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's not use the x-hasura-admin-secret for queries, it's a security risk
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/util/CsvWriter.kt` line 40 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPHdh07A5j0VRUDOCeq:-NPWgl3OCaA2qOGg5E-i:beqwv8n) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/5fd71efd6bed47979ffa544a990c085bf5abefbc/src/main/kotlin/fi/hsl/jore4/hastus/util/CsvWriter.kt#L40)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should rather move this to the class's toString() method
</blockquote></details>

Not really possible, due to using csv specific decimal formatter. I moved the format generation to the NumberWithAccuracy -class.


<!-- Sent from Reviewable.io -->

2023-03-07 20:02 UTC, jarkkoka requested changes
I was wondering if there is any particular reason or known benefits to accessing the database via GraphQL instead of a JDBC connection? Can you elaborate a bit about this design choice in the README?

Second, using inheritance to pass the data for CSV writer and including string construction information in the data object classes seems like a less than great solution to me. In general, data object classes shouldn't care about how they are formatted as strings...

> Reviewed 38 of 45 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-:-NPxeeFGCIWeaxWlmEuk:b-2g0y1v)* status: all files reviewed, 47 unresolved discussions (waiting on @culka and @pallost)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt` line 27 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPbmvCU97fPZVFr5OBy:-NPbmvCV0t1HPVloe-ip:b-kvsdb9) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt#L27)):*
> ```Kotlin
> ) {
> 
>     private val LOGGER = KotlinLogging.logger {}
> ```

Move `LOGGER` object to (inside) the companion object.



_Code quote:_
```Kotlin
   private val LOGGER = KotlinLogging.logger {}
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/HastusData.kt` line 7 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPaiOYfCSUA0ei16edh:-NPaiOYfCSUA0ei16edi:b-h86nuv) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/HastusData.kt#L7)):*
> ```Kotlin
>     /**
>      * @value fieldName identifier of the element in Hastus readable csv
>      */
> ```

IMO, using inheritance to pass type-specific information is not the best solution (far from elegant). The value of this field is not actually instance-specific but class-specific.

IMO, both the `fieldName` member and the `listWithFieldName` method relate to string formatting and are representational in nature, and for this reason they do not strictly belong in the data object classes themselves. Inheriting from `IHastusData` interface itself isn't bad thing per se, but adding string construction concerns to the type hierarchy is usually a bad solution.

So, what would I have done differently? I'd have made IHastusData a sealed interface and then used the following code snippet in `CsvWriter` to derive the `fieldName`:
```
when (hastusDataObj) {
    is Route -> "rvariant" // or Route.FIELD_NAME
    is Stop -> "rvpoint"
}
```



_Code quote:_
```Kotlin
    /**
     * @value fieldName identifier of the element in Hastus readable csv
     */
    abstract val fieldName: String
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/IHastusData.kt` line 3 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPaSaI-6W4qBRaZxMoN:-NPaSaI0-KrBQAE-soNJ:b-28o7k5) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/IHastusData.kt#L3)):*
> ```Kotlin
> package fi.hsl.jore4.hastus.data.hastus
> 
> interface IHastusData {
> ```

There should be a class-level comment what is the purpose of this interface.



_Code quote:_
```Kotlin
IHastusData
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Place.kt` line 11 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPaSz4Z6EgKI5cxAoiY:-NPaSz4Z6EgKI5cxAoiZ:b-1w2v59) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Place.kt#L11)):*
> ```Kotlin
>  */
> class Place(
>     private val identifier: String,
> ```

Hmmm...I don't understand why you don't use data class type here, but instead declare the private members and write custom implementations of `equals` and `hashCode`? Can you elaborate on that? There seems to be a lot of boilerplate code because of not using data classes.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Place.kt` line 15 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPaU4j41Ghy2WRAu5D0:-NPaU4j41Ghy2WRAu5D1:b-iozz46) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Place.kt#L15)):*
> ```Kotlin
> ) : HastusData() {
> 
>     override val fieldName = "place"
> ```

Usually these kind of constants belong to companion object, but I notice that you are using inheritance in data objects to pass information for CSV writing.



_Code quote:_
```Kotlin
override val fieldName = "place"
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Route.kt` line 13 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPxYlew6MFnGU-4L7rJ:-NPxYlew6MFnGU-4L7rK:blxkxb5) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Route.kt#L13)):*
> ```Kotlin
>  * @constructor Create a Route with given values
>  */
> class Route(
> ```

There is a lot of boilerplate code in writing custom `equals` and `hashCode` because of not using `data class`.



_Code quote:_
```Kotlin
Route(
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/RouteVariantPoint.kt` line 31 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPx_Yoh0e2xMgruPVxq:-NPx_Yoh0e2xMgruPVxr:btd4u36) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/RouteVariantPoint.kt#L31)):*
> ```Kotlin
>     init {
>         // Transform distance in meters to a km.mmm formatted string
>         this.specTpDistance = NumberWithAccuracy(specTpDistance / 1000.0, 0, 3)
> ```

I think this whole class could be simplified a lot by making this class a `data class` (and removing `equals` and `hashCode`) and changing the constructor to accept the `specTpDistance` property in the desired format (`NumberWithAccuracy`). `HastusConverter` class should make this data type conversion.

In the `init` block you can then assert if necessary that the `leading` and `numbers` are what they should be.

Now, there is a lot of boilerplate because of writing custom implementations for `equals` and `hashCode`.



_Code quote:_
```Kotlin
    private val specTpDistance: NumberWithAccuracy

    init {
        // Transform distance in meters to a km.mmm formatted string
        this.specTpDistance = NumberWithAccuracy(specTpDistance / 1000.0, 0, 3)
    }
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt` line 34 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPxbXoQ8cY6PFQejDYG:-NPxbXoQ8cY6PFQejDYH:b-a130ki) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt#L34)):*
> ```Kotlin
> 
>     private val gpsX: NumberWithAccuracy
>     private val gpsY: NumberWithAccuracy
> ```

I think this whole class could be simplified a lot by making this class a `data class` (and removing `equals` and `hashCode`) and changing the constructor to accept the `gpsX` and `gpsY` properties in the desired format (`NumberWithAccuracy`). `HastusConverter` class should make this data type conversion.

In the `init` block you can then assert if necessary that the `leading` and `numbers` are what they should be.

Now, there is a lot of boilerplate because of writing custom implementations for `equals` and `hashCode`.



_Code quote:_
```Kotlin
    private val gpsX: NumberWithAccuracy
    private val gpsY: NumberWithAccuracy

    init {
        this.gpsX = NumberWithAccuracy(gpsX, 2, 6)
        this.gpsY = NumberWithAccuracy(gpsY, 2, 6)
    }
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/StopDistance.kt` line 15 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPxcsuqEfMcnNd [...]

2023-03-14 06:39 UTC, pallost approved these changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5)* status: all files reviewed, 39 unresolved discussions (waiting on @culka)



<!-- Sent from Reviewable.io -->

2023-04-24 12:57 UTC, jarkkoka requested changes
Looks very good now! Just added some very minor remarks.

> Reviewed 15 of 41 files at r3, 4 of 12 files at r4, 9 of 13 files at r5, 1 of 2 files at r6, 2 of 6 files at r8, 6 of 6 files at r9, 35 of 35 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-:-NTnKc2F3qUnAPHRYvwV:bkhr1pp)* status: all files reviewed, 50 unresolved discussions (waiting on @culka)

___
*[`README.md` line 40 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NR7gUv3-YYCzV1uP1xd:-NR7gUv45rzEp_XuUkZF:bb7phvt) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/78e5f957e88cf3b9d2485619f7b1244254bb140e/README.md#L40)):*
> ```Markdown
> The returned CSV file follows the Hastus CSV specification.
> 
> ## Technical DocumentationEi
> ```

typo



_Code quote:_
```Markdown
Ei
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripRecord.kt` line 81 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTn42EM5Zi6rBiG0lUE:-NTn42EM5Zi6rBiG0lUF:b-5sahuo) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f913bd802b9f7da6a0ce8f7ccda5acc884ba8f4f/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripRecord.kt#L81)):*
> ```Kotlin
>     }
> 
>     override fun toString(): String {
> ```

Not sure whether custom implementation is needed besides the default one generated automatically for data class?

I'd add a comment about how this `toString` implementation differs from the default one so that this can be maintained in the future?



_Code quote:_
```Kotlin
   override fun toString(): String {
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/jore/JoreJourneyPattern.kt` line 15 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTn4ea8-PvkV0rsqP56:-NTn4ea8-PvkV0rsqP57:bhrnyko) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f913bd802b9f7da6a0ce8f7ccda5acc884ba8f4f/src/main/kotlin/fi/hsl/jore4/hastus/data/jore/JoreJourneyPattern.kt#L15)):*
> ```Kotlin
>     val uniqueLabel: String?,
>     val journeyPatternId: UUID?,
>     val typeOfLine: String,
> ```

`typeOfLine` missing a corresponding @property annotated comment.



_Code quote:_
```Kotlin
val typeOfLine: String,
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/jore/JoreVehicleService.kt` line 9 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTn5W9m3EQrgrHSdPKE:-NTn5W9m3EQrgrHSdPKF:b5aklee) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f913bd802b9f7da6a0ce8f7ccda5acc884ba8f4f/src/main/kotlin/fi/hsl/jore4/hastus/data/jore/JoreVehicleService.kt#L9)):*
> ```Kotlin
>  *
>  * @property name Name of this vehicle service
>  * @property dayType Day type for this vehicle service
> ```

The ID of day type



_Code quote:_
```Kotlin
Day type
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/mapper/JoreConverter.kt` line 27 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTn64hP481OVUTVuyZX:-NTn64hP481OVUTVuyZY:b3rm8bg) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f913bd802b9f7da6a0ce8f7ccda5acc884ba8f4f/src/main/kotlin/fi/hsl/jore4/hastus/data/mapper/JoreConverter.kt#L27)):*
> ```Kotlin
> class JoreConverter {
> 
>     companion object {
> ```

I guess this could be also changed to `object JoreConverter {`, i.e. no separate class and companion object because all methods are declared inside the companion object.



_Code quote:_
```Kotlin
class JoreConverter {

    companion object {
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt` line 41 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTnCJVc8bopetLcAyoV:-NTnCJVc8bopetLcAyoW:blxufbi) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f913bd802b9f7da6a0ce8f7ccda5acc884ba8f4f/src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt#L41)):*
> ```Kotlin
> 
> @Service
> class GraphQLService(private val config: HasuraConfiguration) {
> ```

The injected `config` object is used only once while initialising `client`. Hence, `val` is unnecessary since `config` is used only as a constructor parameter but not as a property.



_Code quote:_
```Kotlin
val
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt` line 60 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTnDAa4DTW5YSHbSQXv:-NTnDAa4DTW5YSHbSQXw:bq73z4v) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f913bd802b9f7da6a0ce8f7ccda5acc884ba8f4f/src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt#L60)):*
> ```Kotlin
> 
>     private fun convertRoutes(
>         routes: List<fi.hsl.jore4.hastus.generated.routeswithhastusdata.route_route>,
> ```

Just add import for `route_route` in order to get rid of fully-qualified name.



_Code quote:_
```Kotlin
fi.hsl.jore4.hastus.generated.routeswithhastusdata.route_route
```
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt` line 96 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTnDhdk3KORmHJ1HKwQ:-NTnDhdk3KORmHJ1HKwR:bmdj2ly) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f913bd802b9f7da6a0ce8f7ccda5acc884ba8f4f/src/main/kotlin/fi/hsl/jore4/hastus/graphql/GraphQLService.kt#L96)):*
> ```Kotlin
> 
>     private fun getStopDistances(
>         routes: List<UUID>,
> ```

`routeIds`



_Code quote:_
```Kotlin
routes
```
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/test/CsvReaderTest.kt` line 93 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTnFpJxAIDCB158JrjX:-NTnFpJy36xAqyP0hqWp:bifh6zr) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f913bd802b9f7da6a0ce8f7ccda5acc884ba8f4f/src/test/kotlin/fi/hsl/jore4/hastus/test/CsvReaderTest.kt#L93)):*
> ```Kotlin
>             2,
>             isVehicleTypeMandatory = false,
>             isBackupTrip = false,
> ```

Clever use of named parameters. :+1: 



_Code quote:_
```Kotlin
            isVehicleTypeMandatory = false,
            isBackupTrip = false,
            isExtraTrip = false
```
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/test/JoreConverterTest.kt` line 33 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTnHFCyEAnZe5Q126Mr:-NTnHFCyEAnZe5Q126Ms:b-axxijn) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f913bd802b9f7da6a0ce8f7ccda5acc884ba8f4f/src/test/kotlin/fi/hsl/jore4/hastus/test/JoreConverterTest.kt#L33)):*
> ```Kotlin
>     val VEHICLE_TYPE_2_ID = UUID.randomUUID()
> 
>     val MONDAY_DAY_TYPE_ID = UUID.randomUUID()
> ```

Add `private` qualifier for these and move inside the companion object.



_Code quote:_
```Kotlin
    val VEHICLE_TYPE_1_KEY = 10
    val VEHICLE_TYPE_1_ID = UUID.randomUUID()

    val VEHICLE_TYPE_2_KEY = 20
    val VEHICLE_TYPE_2_ID = UUID.randomUUID()

    val MONDAY_DAY_TYPE_ID = UUID.randomUUID()
    val FRIDAY_DAY_TYPE_ID = UUID.randomUUID()
```
___
*[`src/test/kotlin/fi/hsl/jore4/hastus/test/RestTest.kt` line 16 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTnHoEZ-cmrlUf7DxAU:-NTnHoEZ-cmrlUf7DxAV:b-j4y129) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f913bd802b9f7da6a0ce8f7ccda5acc884ba8f4f/src/test/kotlin/fi/hsl/jore4/hastus/test/RestTest.kt#L16)):*
> ```Kotlin
> 
> @DisplayName("Test the rest API")
> class RestTest @Autowired constructor() {
> ```

This can be removed since nothing injected into this class.



_Code quote:_
```Kotlin
 @Autowired constructor()
```


<!-- Sent from Reviewable.io -->

2023-05-02 14:54 UTC, culka reviewed
GraphQL is used mainly so we can use the user management of Hasura in one place and do not need to care about user database privileges in multiple places.

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-:-NSjlwtd7pUTtJf5AWfC:b-4q9usx)* status: all files reviewed, 49 unresolved discussions (waiting on @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt` line 27 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPbmvCU97fPZVFr5OBy:-NSjmXDT380gCy0jtLPB:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/api/ExportController.kt#L27)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Move `LOGGER` object to (inside) the companion object.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/HastusData.kt` line 7 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPaiOYfCSUA0ei16edh:-NTY-2PvB8OP2r79XLax:b-lgiuqu) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/HastusData.kt#L7)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO, using inheritance to pass type-specific information is not the best solution (far from elegant). The value of this field is not actually instance-specific but class-specific.

IMO, both the `fieldName` member and the `listWithFieldName` method relate to string formatting and are representational in nature, and for this reason they do not strictly belong in the data object classes themselves. Inheriting from `IHastusData` interface itself isn't bad thing per se, but adding string construction concerns to the type hierarchy is usually a bad solution.

So, what would I have done differently? I'd have made IHastusData a sealed interface and then used the following code snippet in `CsvWriter` to derive the `fieldName`:
```
when (hastusDataObj) {
    is Route -> "rvariant" // or Route.FIELD_NAME
    is Stop -> "rvpoint"
}
```
</blockquote></details>

`fieldName` is her mainly to force every data type to have one.

I actually did not know what sealed class did. The fact that it's possible to know all class implementations does solve this in a better way. :+1:
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/IHastusData.kt` line 3 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPaSaI-6W4qBRaZxMoN:-NTXyaQyDV-XE44IVepY:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/IHastusData.kt#L3)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

There should be a class-level comment what is the purpose of this interface.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Place.kt` line 11 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPaSz4Z6EgKI5cxAoiY:-NTXkPCpD_BWImC2TXeE:bxw88) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Place.kt#L11)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Hmmm...I don't understand why you don't use data class type here, but instead declare the private members and write custom implementations of `equals` and `hashCode`? Can you elaborate on that? There seems to be a lot of boilerplate code because of not using data classes.
</blockquote></details>

For some reason I completely forgot the existence of data classes when writing these. The CSV line classes should absolutely be data classes.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Place.kt` line 15 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPaU4j41Ghy2WRAu5D0:-NTXzOGU5r0eTmNxMxVu:b467vgr) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Place.kt#L15)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Usually these kind of constants belong to companion object, but I notice that you are using inheritance in data objects to pass information for CSV writing.
</blockquote></details>

Yes, it's not possible to override companion object data. 
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Route.kt` line 13 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPxYlew6MFnGU-4L7rJ:-NTYr4C8-Z3qbssXto8_:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Route.kt#L13)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

There is a lot of boilerplate code in writing custom `equals` and `hashCode` because of not using `data class`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/RouteVariantPoint.kt` line 31 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPx_Yoh0e2xMgruPVxq:-NTYrPeqBGWUkYFwqC3G:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/RouteVariantPoint.kt#L31)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think this whole class could be simplified a lot by making this class a `data class` (and removing `equals` and `hashCode`) and changing the constructor to accept the `specTpDistance` property in the desired format (`NumberWithAccuracy`). `HastusConverter` class should make this data type conversion.

In the `init` block you can then assert if necessary that the `leading` and `numbers` are what they should be.

Now, there is a lot of boilerplate because of writing custom implementations for `equals` and `hashCode`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt` line 34 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPxbXoQ8cY6PFQejDYG:-NTYrty3A0BUflpFDaYX:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/Stop.kt#L34)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think this whole class could be simplified a lot by making this class a `data class` (and removing `equals` and `hashCode`) and changing the constructor to accept the `gpsX` and `gpsY` properties in the desired format (`NumberWithAccuracy`). `HastusConverter` class should make this data type conversion.

In the `init` block you can then assert if necessary that the `leading` and `numbers` are what they should be.

Now, there is a lot of boilerplate because of writing custom implementations for `equals` and `hashCode`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/StopDistance.kt` line 15 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NPxcsuqEfMcnNdPbwoA:-NTYrymh-lZuiMpKq-RW:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/2b303ff1a7c5867b896cf247ed8525572edf15c1/src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/StopDistance.kt#L15)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think this class could be changed to `data class`. Then you can remove the custom implementations of `equals` and `hashCode` (error-prone code).
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/hastus/TripRecord.kt` line 81 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTn42EM5Zi6rBiG0lUE:-NURsr0gAgu8W0OJq7MS:b-gf3zkj) ([raw file](https://github.com/HSLdevcom/jor [...]

2023-05-04 06:41 UTC, jarkkoka approved these changes
Ok, I see. In jore3-importer has its own dedicated database role/user but we had to make hasura role a member of that role in order to enable both Hasura and jore3-importer to have ownership to database tables.

> Reviewed 18 of 18 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-:-NUVdtICCBZcqMBOkKPU:baehbtc)* status: all files reviewed, 3 unresolved discussions (waiting on @culka)

___
*[`src/main/kotlin/fi/hsl/jore4/hastus/data/mapper/JoreConverter.kt` line 27 at r10](https://reviewable.io/reviews/HSLdevcom/jore4-hastus/5#-NTn64hP481OVUTVuyZX:-NUVebXn756H2QUldbZ0:bkh8ejt) ([raw file](https://github.com/HSLdevcom/jore4-hastus/blob/f913bd802b9f7da6a0ce8f7ccda5acc884ba8f4f/src/main/kotlin/fi/hsl/jore4/hastus/data/mapper/JoreConverter.kt#L27)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmmm...seems not in the revision currently being reviewed.


<!-- Sent from Reviewable.io -->

2023-05-04 10:40 UTC, merged